### ISSUE TITLE
Transfer to typelevel github org (make sure docs work)

### ISSUE THREAD

**Issue by jatcwang** [typelevel/doobie#1973]
Top priority is to make sure doc site works.

**Comment by valencik** [comment]
Hey @jatcwang!
(cc'ing @armanbilge as [he was advising on the move](https://github.com/typelevel/doobie/issues/1922#issuecomment-2325057399))

Happy to see doobie migrated over to the typelevel github org! 🎉 
I suppose that means this issue is technically complete.

I'm hoping however you can comment on the plans for publishing going forward.

1. Is the plan to publish the next RC from Typelevel GitHub but still at the org.tpolecat coordinates?
2. Do you want to eventually do RC releases with `org.typelevel` coords?

I think we should document the plan / intent, and then we can post a quick update on the Typelevel blog so people know what to expect (I can write that up).

**Comment by jatcwang** [comment]
Hi @valencik thanks :) Yes the plan is for the upcoming 1.0-RC6 will be the last release published to org.tpolecat coordinate. After that we'll be migrating the package name to org.typelevel.doobie (#1972) and publish to `org.typelevel` coordinate.

:+1: on the typelevel blog too. I'll draft a rough post once we have all the pieces (scalafix rule etc) and I'll reach out to you to polish it. Many thanks!
