### ISSUE TITLE
Plans to support synchronous IO over Virtual Threads?

### ISSUE THREAD

**Issue by coryfklein** [typelevel/doobie#2096]
Similar to how [Tapir provides a synchronous netty server operating with the `Identity[T]` monad](https://tapir.softwaremill.com/en/latest/server/netty.html#direct-style), operating using Loom's Virtual Threads, would doobie ever consider providing a synchronous execution model over the `Id[T]` monad?

Right now, the [Using Your Own Monad](https://typelevel.org/doobie/docs/03-Connecting.html#using-your-own-target-monad) documentation says:

> you can use any monad M[_] given cats.effect.Async[M]

And the code confirms that the monad **must** be Async.

I understand there are caveats and acknowledgements one must make when handing complete control of threading over to the JVM, but I suspect Virtual Threads will be sufficient for many use cases, and the improvement to readability (not dealing with the async monads!) is dramatic, and would be very helpful for adoption in groups where use of such monads is not the norm.

Is doobie open to this as a possibility?

**Comment by satorg** [comment]
As you pointed out, the documentation suggests that any `M[_]` can be used as soon as it implements `Async`.
So the question is rather – is it even feasible to implement `Async` for the identity monad?

The problem here is that `Async` is not just about wrapping of blocking calls. It handles many other aspects of code execution, e.g. safe exception handling, safe parallel execution, cancellation with backpressure, etc. Let alone referential transparency (which the identity monad just cannot do, btw).

That said, catseffect's `IO` _can_ be used with virtual threads (see typelevel/cats-effect#3869 for details).
It just means that you cannot evade `IO` context for that (for good reason).

**Comment by jatcwang** [comment]
Another consideration is that your JDBC driver needs to be virtual-threads-ready too. For example, pgjdbc before version 42.6.0 still uses synchronized methods which causes carrier threads to be pinned.

**Comment by coryfklein** [comment]
Thanks for adding all that context @satorg and @jatcwang. I think the above are all good and reasonable points.

I get that the `Async` monad provides more benefits than just an abstraction over asynchronous execution, and I find value in all these features:

> safe exception handling, safe parallel execution, cancellation with backpressure, etc. Let alone referential transparency

The documentation, in teaching doobie, makes liberal use of `unsafeRunSync`. I presume this is done to make learning to use doobie more approachable for beginners. I sympathize with this approach, given that most teams writing Scala have some burden of educating newcomers to both the language and functional programming in general.

I think my team would benefit from using the `Async` monad. But right now the bulk of our code – despite being Scala – looks more like synchronous (blocking) Java and I'm faced with identifying a road that leads us to eventually learning and understanding monadic styles, effect systems, etc.

I'm liking the choice of doobie right now because I can sort of "wrap" doobie in a synchronous, unsafe, blocking API that looks friendly to my colleagues, with the idea that I can over time introduce more safe and "advanced" and usage in bite sized pieces as I have time to mentor and educate.

Similar to how doobie provides `unsafeRunSync` to allow a graded learning of doobie, do you think (with your inside knowledge) that allowing an "unsafe Identity" monad could help teams like mine? I'm so new to doobie that I can't even judge whether such a thing would provide any benefit over my current idea of "user friendly" doobie wrappers a la:

```
def queryOne[T: Read](fragment: Fragment): T =
  fragment.query[T].unique.transact(xa).unsafeRunSync()

def exampleUsage(id: Long): SomeData =
  queryOne(sql"SELECT * FROM mytable WHERE id = $id;")
```

**Comment by jatcwang** [comment]
I would say the docs uses `unsafeRunSync` because that's the only way you can directly execute an IO directly in REPL.

I feel that "unsafe Identity" is probably going to be quite confusing/hacky to implement and may end up hurting the maintainability/understandability of your project. The wrapper approach you're doing right now is perfectly fine IMO, it's something I've done so myself.

I think cats-effect support will come in 3.6.0 (not yet released), so perhaps it's worth doing some benchmarking to see if the lack of virtual threads support is a dealbreaker for now.

**Comment by coryfklein** [comment]
@jatcwang Thank you for going out of your way to read, parse, and respond to my feedback and questions. I appreciate it.
